language: bash
services: docker

env:
  - VERSION=VARNISH VARIANT=4
  - VERSION=APACHE VARIANT=2.4
  - VERSION=PHP-FPM VARIANT=7.2_PROD
  - VERSION=PHP-FPM VARIANT=7.2_DEV
  - VERSION=NODE VARIANT=10.15


before_script:
  - env | sort
  - cd "${VERSION}"
  - cd "${VARIANT}"

script:
  - travis_retry docker build -t test_image .
  - docker run -d -p 127.0.0.1:80:80 --name test_container test_image
  - docker ps | grep -q test_container