language: bash
services: docker

env:
  - VERSION=VARNISH VARIANT=VARNISH/4
  - VERSION=APACHE VARIANT=APACHE/2.4
  - VERSION=PHP-FPM VARIANT=PHP-FPM7.2_PROD
  - VERSION=PHP-FPM VARIANT=PHP-FPM7.2_DEV
  - VERSION=NODE VARIANT=NODE/10.15


before_script:
  - env | sort
  - cd "${VERSION}"

script:
  - travis_retry docker build -t test_image .
  - docker run -d -p 127.0.0.1:80:80 --name test_container test_image
  - docker ps | grep -q test_container